### ISSUE TITLE
[Question] Centered widget or Scrollable widget

### ISSUE THREAD

**Issue by JCKodel** [pingbird/boxy#23]
Scenario:

I'm using Flutter Desktop and Web, so the window size is totally arbitrary.

I want to create a login screen that have a `Column` containing a logo, title, e-mail text input, password text input, forgot password link and a button.

What I need is:

* If the widget doesn't fit on the screen, encapsulate it with a `SingleChildScrollView`.
* If the widget fits the screen, encapsulate it with a `Center`, so it always appears in the middle of the screen.

How to achieve that?

**Comment by pingbird** [comment]
Simply wrapping SingleChildScrollView in Center should work fine

**Comment by ForeverAngry** [comment]
@pingbird is there a way to paint edges between 2 tree nodes at different or the same level?


![Screenshot_20231008_110247_GitHub.jpg](https://github.com/pingbird/boxy/assets/61765732/050359d3-6006-4be7-9229-6223433caf6d)

**Comment by pingbird** [comment]
@ForeverAngry That would require a graph rendering algorithm like [graphviz](https://graphviz.org/) which is not easy.

These GitHub issues are for bugs and feature requests in Boxy, not help questions, you should ask on StackOverflow or the Flutter discord instead of hijacking someone else's issue.
