### ISSUE TITLE
`RedirectPointer` is not importable

### ISSUE THREAD

**Issue by mattermoran** [pingbird/boxy#29]
Heya. 
I saw the new release with 2 widgets added but noticed I can't import the `RedirectPointer` and digging a bit showed that it was exported differently compared to other widgets. 
`RedirectPointer` -> `export 'package:boxy/redirect_pointer.dart';`
`Scale` and others -> `export 'src/scale.dart';`

I guess just fixing the export should do the trick. 

P.S any reason why the package version was not bumped to `2.2.0` as these are the new features and not just bug fixes? 
it's not really that important it's just that I like to manually update packages and seeing minor updates more likely to make me go to changelog :)

**Comment by pingbird** [comment]
> P.S any reason why the package version was not bumped to 2.2.0 as these are the new features and not just bug fixes?
it's not really that important it's just that I like to manually update packages and seeing minor updates more likely to make me go to changelog :)

I generally version based on chance of breaking something and this release did not change any existing behavior so it got a revision bump instead of a minor bump
